### ISSUE TITLE
batch_size of the original setting

### ISSUE THREAD

**Issue by Nickisdope** [fpv-iplab/stillfast#4]
Hi, I am trying to reproduce the results. 

In the paper it says u trained with a batch size of 8 on four V100s. Does it mean 8 for each GPU thus 32 in total? Or does it mean 2 for each GPU and 8 in total?

Cos in the config file of this codebase you set batch_size = 14, probably meaning 3 for each GPU when using 4 GPUs, which confused me.

**Comment by francescoragusa** [comment]
Hi @Nickisdope, we trained StillFast with a batch_size = 14, that means 14 for each GPU, 14*4 = 56.
In the supplementary material the reported batch_size is wrong, I'm revising this detail and update the arXiv. Thank you very much.
Let me know, if you need other information.
